AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template used for provisioning SAM artifact storage for environments 
  that require slow transitions and expiration of build artifacts.
Parameters:
  AppName:
    Type: String
    Description: "Name of application."
    AllowedPattern: ".+"
    Default: "ninja-buckets-c"

  Environment:
    Type: String
    Description: "Environment code of deployment (dev, uat, prod)"
    AllowedPattern: ".+"
    AllowedValues:
      - "dev"
      - "uat"
      - "prod"

#  ____
# |  _ \ ___  ___  ___  _   _ _ __ ___ ___  ___
# | |_) / _ \/ __|/ _ \| | | | '__/ __/ _ \/ __|
# |  _ <  __/\__ \ (_) | |_| | | | (_|  __/\__ \
# |_| \_\___||___/\___/ \__,_|_|  \___\___||___/

Resources:
  SamArtifactStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Join ["-", [!Ref AppName, !Ref Environment, "sam-artifacts-c"]]
      LifecycleConfiguration:
        Rules:
          - Id: SetToStandardIAAfterAYear
            Status: Enabled
            Transitions:
              - TransitionInDays: "365"
                StorageClass: STANDARD_IA
          - Id: SetToGlacierAfterThreeYears
            Status: Enabled
            Transitions:
              - TransitionInDays: "1095"
                StorageClass: GLACIER
          - Id: DeleteArtifactsAfterSevenYears
            Status: "Enabled"
            ExpirationInDays: 2555
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: "ENVIRONMENT"
          Value: !Ref Environment
        - Key: "APP"
          Value: !Ref AppName
